steps: 
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ppap:$COMMIT_SHA', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/ppap:$COMMIT_SHA']
logsBucket: 'gs://bucket-db-capstone/logs'    